### ISSUE TITLE
WNDR4300 affected

### ISSUE THREAD

**Issue by Netspider** [darkarnium/secpub#1]
Hi!
as I did not find an option to send you an email I'll do it this way...
I have a WNDR4300 and your skript printed the correct wpa name/key, admin password, serial number and firmware version (1.0.1.60, latest).
I wrote to the netgear support with a link to this repository, maybe it works when many people open a ticket?

Thanks for finding this!
Ronny Lindner

**Comment by darkarnium** [comment]
Hi there,

Thank you for that additional confirmation, I will update the write-up on with this information. Would you like me to provide your full name in the document, or is there another way you would prefer to
be addressed?

Cheers,
Peter

**Comment by Netspider** [comment]
full name is ok - I got the confirmation from the support that they have routed the problem to the development team.

**Comment by darkarnium** [comment]
Not a problem, I've updated the list of affected devices. A few others have said that they have done the same - with regards to contacting NetGear - so hopefully an official fix will be available soon.

Cheers.
