### ISSUE TITLE
cannot load such file 'restclient'

### ISSUE THREAD

**Issue by tabbytabby** [darkarnium/secpub#4]
Which Restclient are you using? 
`require': cannot load such file -- restclient (LoadError)
gem install restclient doesn't help

**Comment by darkarnium** [comment]
On my development machine I'm using rest-client version 1.7.2, a `gem install rest-client` should do it.

Cheers,
Peter

**Comment by tabbytabby** [comment]
Thank you! That worked.

**Comment by darkarnium** [comment]
Not a problem.

Cheers,
Peter
