### ISSUE TITLE
WNR2200  - vulnerable

### ISSUE THREAD

**Issue by marcinpraczko** [darkarnium/secpub#8]
Hi,  
Just tested this on WNR2200 and is working, default run - no special paramters.

```
[*] Model Number: wnr2200
[*] Firmware Version: V1.0.1.76
```

Best regards.

**Comment by darkarnium** [comment]
Hi there,

Thank you for that additional confirmation, I will update the write-up on with this information. Would you like me to provide your full name in the document, or is there another way you would prefer to
be addressed?

Cheers,
Peter

**Comment by marcinpraczko** [comment]
Hi there, 

Full name is OK, Please use Marcin Praczko

Cheers,
Marcin

**Comment by darkarnium** [comment]
Hello there,

Cheers for the addition. Sorry it's taken so long to get back to you, I will update the list now.

Thanks again! :)
Peter
